name: Create PR to Staging and Main

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Git Pull Origin
        run: |
          git pull origin ${{ github.head_ref }}

      - name: Create PR to Staging
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "stg"
          branch: ${{ github.head_ref }}

      - name: Create PR to Main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "main"
          branch: ${{ github.head_ref }}